# docker-compose.yml

services:

  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psw231
      - POSTGRES_DB=recommendation_db
    ports:
      - "5435:5435"
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5435
      DB_USERNAME: postgres
      DB_PASSWORD: psw231
      DB_DATABASE: recommendation_db

volumes:
  postgres_data:
