-- AlterTable
ALTER TABLE "Movie" ALTER COLUMN "oyuncular" SET NOT NULL,
ALTER COLUMN "oyuncular" SET DATA TYPE TEXT,
ALTER COLUMN "yonetmen" SET NOT NULL,
ALTER COLUMN "yonetmen" SET DATA TYPE TEXT;
